version: '3.3'

services:
  postgres:
    container_name: postgres_container
    image: postgres:14.3
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: n3t4dm1ndb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
